from pathlib import Path
from html import escape
from PIL import Image
import json

ROOT = Path(__file__).parent
ASSETS = ROOT / 'assets'
ASSETS.mkdir(exist_ok=True)
SRC = Path(__file__).parents[1] / 'generated_images'
for stem, file in {
    'mandap-concept': 'exec-058c1a0e-aa22-43ae-8d8a-a3b8ab2cdeeb.png',
    'ceremony-concept': 'exec-b985f726-91c8-4fab-b6dc-1dc84d0a739e.png',
    'entrance-concept': 'exec-9ca1e271-0c7c-4f27-aa5b-e3c8e985c9a0.png',
}.items():
    image = Image.open(SRC / file).convert('RGB')
    for width in (600, 1100, 1600):
        if width > image.width: continue
        out = image.resize((width, round(image.height * width / image.width)), Image.Resampling.LANCZOS)
        out.save(ASSETS / f'{stem}-{width}.webp', 'WEBP', quality=80, method=6)

BASE = 'https://cloudempiretech.github.io/saha-decorators-kolkata/'
PHONE = '+919830127369'
TEL = f'tel:{PHONE}'
WA = 'https://wa.me/919830127369'
MAP = 'https://www.google.com/maps/search/?api=1&query=59%2F60%20Bagmari%20Road%20Kankurgachi%20Kolkata%20700054'

(ASSETS / 'logo.svg').write_text('''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 280 70" role="img" aria-labelledby="t"><title id="t">Saha Decorators proposed logo</title><defs><linearGradient id="g" x2="1" y2="1"><stop stop-color="#e9b972"/><stop offset="1" stop-color="#a96132"/></linearGradient></defs><path d="M12 58V29C12 13 25 5 38 4c13 1 26 9 26 25v29M20 58V31c0-11 8-18 18-20 10 2 18 9 18 20v27M38 18v31m-12-8 12 11 12-11" fill="none" stroke="url(#g)" stroke-width="3" stroke-linecap="round"/><circle cx="38" cy="34" r="4" fill="#d39445"/><text x="79" y="33" font-family="Georgia,serif" font-size="28" fill="#f7ede0">Saha</text><text x="80" y="54" font-family="Arial,sans-serif" letter-spacing="4" font-size="11" fill="#e1b277">DECORATORS</text></svg>''')
(ASSETS / 'favicon.svg').write_text('''<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect width="64" height="64" rx="14" fill="#2d1218"/><path d="M12 53V29C12 17 21 9 32 7c11 2 20 10 20 22v24M20 53V30c0-7 5-13 12-15 7 2 12 8 12 15v23M32 24v29m-10-9 10 9 10-9" fill="none" stroke="#e9b972" stroke-width="3" stroke-linecap="round"/><circle cx="32" cy="33" r="4" fill="#e9b972"/></svg>''')

def picture(stem, alt, cls='', eager=False):
    srcset=f'assets/{stem}-600.webp 600w, assets/{stem}-1100.webp 1100w'
    if stem=='mandap-concept': srcset+=f', assets/{stem}-1600.webp 1600w'
    return f'''<picture class="{cls}"><source type="image/webp" srcset="{srcset}" sizes="(max-width: 700px) 100vw, 50vw"><img src="assets/{stem}-1100.webp" alt="{escape(alt)}" width="1100" height="1000" loading="{'eager' if eager else 'lazy'}" decoding="async"></picture>'''

def icon(kind):
    paths = {
        'phone':'<path d="M6 3h4l2 5-2.5 2a16 16 0 0 0 5 5L17 12l5 2v4a3 3 0 0 1-3 3C10 21 3 14 3 6a3 3 0 0 1 3-3Z"/>',
        'pin':'<path d="M12 22s7-6.2 7-12a7 7 0 1 0-14 0c0 5.8 7 12 7 12Z"/><circle cx="12" cy="10" r="2.5"/>',
        'arrow':'<path d="M4 12h16m-7-7 7 7-7 7"/>',
        'whatsapp':'<path d="M20.1 3.9A9.9 9.9 0 0 0 4.5 15.8L3 21l5.3-1.4A9.9 9.9 0 1 0 20.1 3.9Z"/><path d="M8.2 7.8c-.2-.4-.4-.4-.7-.4h-.6c-.2 0-.5.1-.7.4-.2.3-.8 1-.8 2.4s.9 2.7 1 2.9c.1.2 1.8 2.8 4.3 3.8.6.3 1.1.4 1.5.5.6.2 1.2.2 1.7.1.5-.1 1.6-.7 1.8-1.4.2-.7.2-1.3.2-1.4-.1-.1-.3-.2-.7-.4l-1.9-.9c-.3-.1-.5-.2-.7.2-.2.3-.8 1-1 1.2-.2.2-.4.2-.7.1-.4-.2-1.5-.6-2.8-1.8-1-.9-1.7-2-1.9-2.4-.2-.3 0-.5.1-.7l.5-.6.3-.5c.1-.2 0-.4 0-.6l-.9-2.2Z"/>',
    }
    return f'<svg viewBox="0 0 24 24" aria-hidden="true" fill="none" stroke="currentColor" stroke-width="1.8" stroke-linecap="round" stroke-linejoin="round">{paths[kind]}</svg>'

nav = [('index.html','Home'),('about.html','About'),('services.html','Services'),('mandap-decoration.html','Mandap design'),('concept-gallery.html','Concept gallery'),('faq.html','FAQ'),('contact.html','Contact')]

def page(file, title, desc, body):
    url = BASE if file == 'index.html' else BASE + file
    schema = {'@context':'https://schema.org','@type':'LocalBusiness','name':'Saha Decorators','url':BASE,'telephone':PHONE,'address':{'@type':'PostalAddress','streetAddress':'59/60 Bagmari Road','addressLocality':'Kankurgachi, Kolkata','addressRegion':'West Bengal','postalCode':'700054','addressCountry':'IN'},'description':'Event and mandap decoration enquiries in Kolkata.'}
    navhtml=''.join(f'<a href="{h}"'+(' aria-current="page"' if h==file else '')+f'>{n}</a>' for h,n in nav)
    html=f'''<!doctype html><html lang="en-IN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>{escape(title)}</title><meta name="description" content="{escape(desc)}"><link rel="canonical" href="{url}"><link rel="icon" type="image/svg+xml" href="assets/favicon.svg"><meta name="theme-color" content="#2d1218"><meta property="og:title" content="{escape(title)}"><meta property="og:description" content="{escape(desc)}"><meta property="og:url" content="{url}"><meta property="og:type" content="website"><link rel="stylesheet" href="assets/style.css"><script type="application/ld+json">{json.dumps(schema,separators=(',',':'))}</script><script src="assets/site.js" defer></script></head><body data-page="{file}"><a class="skip" href="#main">Skip to content</a><div class="page-shell"><header class="site-header"><div class="header-inner"><a class="brand" href="index.html" aria-label="Saha Decorators home"><img src="assets/logo.svg" alt="Saha Decorators proposed logo" width="240" height="60"></a><button class="menu-toggle" type="button" aria-label="Open menu" aria-expanded="false" aria-controls="site-nav"><span></span><span></span><span></span></button><nav id="site-nav" aria-label="Main navigation">{navhtml}</nav><div class="header-actions"><a class="header-call" href="{TEL}" aria-label="Call Saha Decorators at +91 98301 27369">{icon('phone')}<span>Call to discuss</span></a><a class="header-whatsapp" href="{WA}" target="_blank" rel="noopener noreferrer" aria-label="Message Saha Decorators on WhatsApp" title="Message Saha Decorators on WhatsApp">{icon('whatsapp')}</a></div></div></header><main id="main">{body}</main><footer class="site-footer"><div class="footer-top"><div><a class="brand" href="index.html"><img src="assets/logo.svg" alt="Saha Decorators proposed logo" width="240" height="60"></a><p>Decoration ideas shaped around the occasion, the space and the conversation.</p></div><div><h2>Explore</h2>{''.join(f'<a href="{h}">{n}</a>' for h,n in nav[1:])}</div><div><h2>Get in touch</h2><a href="{TEL}">{icon('phone')} +91 98301 27369</a><a href="{WA}" target="_blank" rel="noopener noreferrer" aria-label="Message Saha Decorators on WhatsApp">{icon('whatsapp')} Message on WhatsApp</a><a href="{MAP}" target="_blank" rel="noopener noreferrer">{icon('pin')} 59/60 Bagmari Road, Kolkata</a></div></div><div class="footer-bottom"><span>© 2026 Saha Decorators. All rights reserved.</span><span>Developed by <a href="https://cloudempire.tech/" target="_blank" rel="noopener noreferrer">Cloudempire</a></span></div></footer></div><a class="floating-call" href="{TEL}" aria-label="Call Saha Decorators" title="Call Saha Decorators">{icon('phone')}</a><a class="floating-whatsapp" href="{WA}" target="_blank" rel="noopener noreferrer" aria-label="Message Saha Decorators on WhatsApp" title="Message Saha Decorators on WhatsApp">{icon('whatsapp')}</a></body></html>'''
    (ROOT/file).write_text(html)

def intro(kicker,title,lead): return f'<section class="inner-hero"><div class="orb orb-one"></div><div class="container"><p class="eyebrow reveal">{kicker}</p><h1 class="reveal">{title}</h1><p class="lead reveal">{lead}</p></div></section>'
def cta(title='Let’s discuss your occasion',text='Tell us the date, venue and the kind of setting you have in mind. We can talk through the possibilities before anything is planned.'):
    return f'<section class="cta-block reveal"><div class="container cta-inner"><div><p class="eyebrow">The next step</p><h2>{title}</h2><p>{text}</p></div><div class="cta-actions"><a class="button light" href="contact.html#enquiry">Start an enquiry {icon("arrow")}</a><a class="button whatsapp-button" href="{WA}" target="_blank" rel="noopener noreferrer">{icon("whatsapp")} Send enquiry</a></div></div></section>'

home=f'''<section class="hero"><div class="hero-media">{picture('mandap-concept','Illustration of a marigold and ivory ceremonial mandap concept, not a completed Saha Decorators project','hero-picture',True)}</div><div class="hero-shade"></div><div class="hero-content container"><p class="eyebrow hero-in">Kolkata · Event & mandap decoration</p><h1 class="hero-in">A setting for<br><em>the moments</em><br>that matter.</h1><p class="hero-in">Explore decoration ideas, then speak with Saha Decorators about your occasion and venue.</p><div class="hero-actions hero-in"><a class="button" href="contact.html#enquiry">Discuss your event {icon('arrow')}</a><a class="button whatsapp-button" href="{WA}" target="_blank" rel="noopener noreferrer">{icon('whatsapp')} Send enquiry</a><a class="text-link" href="concept-gallery.html">Explore concepts ↗</a></div><p class="hero-note hero-in">Concept illustration · not a photograph of completed work</p></div><div class="hero-caption">SAHA DECORATORS <span>01 / 03</span></div></section>
<section class="section warm"><div class="container split"><div class="reveal"><p class="eyebrow">The idea</p><h2>Spaces become<br><em>part of the story.</em></h2><p>From a mandap to a welcoming event entrance, decoration helps set the tone. Saha Decorators is listed for decorating and mandap work near Bagmari Road in Kolkata. The right next step is a conversation about your actual venue and requirements.</p><a class="inline-link" href="about.html">Meet the business {icon('arrow')}</a></div><div class="image-frame reveal">{picture('entrance-concept','Illustration of a festive decorated entrance concept, not a completed project')}<span class="media-tag">Illustration · design concept</span></div></div></section>
<section class="section dark"><div class="container"><p class="eyebrow reveal">Explore the possibilities</p><div class="section-heading reveal"><h2>Decoration with an<br><em>occasion in mind.</em></h2><p>Start with the space, the celebration and your preferred atmosphere. Confirm the precise scope directly with the team.</p></div><div class="card-grid"><a class="service-card reveal" href="mandap-decoration.html"><span class="number">01</span><h3>Mandap decoration</h3><p>Discuss a ceremonial focal point suited to your venue.</p><span class="card-arrow">↗</span></a><a class="service-card reveal" href="services.html"><span class="number">02</span><h3>Event decoration</h3><p>Explore an overall setting for gatherings and celebrations.</p><span class="card-arrow">↗</span></a><a class="service-card reveal" href="concept-gallery.html"><span class="number">03</span><h3>Design direction</h3><p>Use our labeled concepts to start a conversation about style.</p><span class="card-arrow">↗</span></a></div></div></section>
<section class="section warm"><div class="container split reverse"><div class="image-frame reveal">{picture('ceremony-concept','Illustration of an ivory-column wedding mandap concept, not a completed project')}<span class="media-tag">Illustration · design concept</span></div><div class="reveal"><p class="eyebrow">A considered beginning</p><h2>Bring your<br><em>brief to life.</em></h2><p>Tell us what you are celebrating, where it will take place and what visual direction you have in mind. A direct call can clarify availability, options and the next steps.</p><a class="button outline" href="contact.html">Make an enquiry {icon('arrow')}</a></div></div></section>{cta()}'''
page('index.html','Saha Decorators | Event & Mandap Decoration in Kolkata','Explore event and mandap decoration with Saha Decorators, Bagmari Road, Kolkata. View clearly labeled concepts and call to discuss your occasion.',home)

about=intro('About Saha Decorators','A local name in<br><em>decoration.</em>','Saha Decorators is listed at 59/60 Bagmari Road, Kankurgachi, Kolkata, for decorating and mandap work.')+f'''<section class="section warm"><div class="container split"><div class="reveal"><h2>Start with what is<br><em>verifiable.</em></h2><p>Independent local listings connect Saha Decorators with decorating contractor and mandap decorator categories at the same Bagmari Road address. The business phone in those listings matches the contact number supplied for this project.</p><p>We have kept this website focused on those details. Specific styles, availability, timelines and quotes should be discussed directly rather than assumed.</p><a class="inline-link" href="contact.html">Contact the team {icon('arrow')}</a></div><div class="image-frame reveal">{picture('mandap-concept','Illustration of a ceremonial mandap design idea, not an actual project')}<span class="media-tag">Illustration · design concept</span></div></div></section>{cta()}'''
page('about.html','About Saha Decorators | Kolkata','Learn about Saha Decorators and its verified Bagmari Road location, decorating categories and direct enquiry options.',about)

services=intro('Services to discuss','Decoration begins<br><em>with your brief.</em>','The exact design and scope depend on your event, venue and conversation with the business.')+f'''<section class="section warm"><div class="container"><div class="service-row reveal"><span class="row-no">01</span><div><h2>Mandap decoration</h2><p>Ask about a ceremony setting that complements your venue and occasion. The business appears in local mandap decorator listings.</p><a class="inline-link" href="mandap-decoration.html">Explore this service {icon('arrow')}</a></div>{picture('ceremony-concept','Illustration of a mandap decoration direction, not completed work')}</div><div class="service-row reveal"><span class="row-no">02</span><div><h2>Event decoration</h2><p>Discuss the overall presentation of a gathering, from the focal area to guest-facing details. Confirm the services needed with the team.</p><a class="inline-link" href="contact.html">Ask about your event {icon('arrow')}</a></div>{picture('entrance-concept','Illustration of an event entrance idea, not completed work')}</div></div></section>{cta()}'''
page('services.html','Decoration Services | Saha Decorators Kolkata','Discuss mandap and event decoration requirements with Saha Decorators in Kolkata. View conceptual directions and contact the team.',services)

mandap=intro('Mandap decoration','A focal point for<br><em>your ceremony.</em>','Discuss a mandap setting that works with the venue, occasion and atmosphere you want to create.')+f'''<section class="section warm"><div class="container split"><div class="reveal"><h2>Shape the space<br><em>around the moment.</em></h2><p>Saha Decorators is listed as a mandap decorator in Kolkata. A useful first conversation covers the event date, venue, available space, and the look you have in mind.</p><p>The visual shown here is an illustration for inspiration. It is not a photograph of the business’s past work or a promise of a specific setup.</p><a class="button outline" href="contact.html">Discuss mandap decoration {icon('arrow')}</a></div><div class="image-frame reveal">{picture('ceremony-concept','Illustration of a floral and draped mandap concept, not a Saha Decorators installation')}<span class="media-tag">Illustration · design concept</span></div></div></section><section class="section dark"><div class="container"><p class="eyebrow">Prepare an enquiry</p><h2 class="reveal">A few details help<br><em>start the conversation.</em></h2><div class="card-grid"><div class="service-card reveal"><span class="number">01</span><h3>Occasion</h3><p>What is the event and what kind of setting do you imagine?</p></div><div class="service-card reveal"><span class="number">02</span><h3>Venue</h3><p>Where will the decoration be installed, and how much space is available?</p></div><div class="service-card reveal"><span class="number">03</span><h3>Date</h3><p>Share the date so availability can be discussed directly.</p></div></div></div></section>{cta()}'''
page('mandap-decoration.html','Mandap Decoration Enquiries | Saha Decorators Kolkata','Ask Saha Decorators about mandap decoration in Kolkata. Prepare venue and event details and contact the team directly.',mandap)

gallery=intro('Concept gallery','Ideas to begin<br><em>a conversation.</em>','These original illustrations suggest possible moods. They do not depict actual products, staff, premises or completed Saha Decorators work.')+f'''<section class="section warm"><div class="container gallery-grid"><figure class="gallery-item large reveal">{picture('mandap-concept','Illustration of an ivory-draped marigold ceremonial stage concept')}<figcaption><strong>Mandap atmosphere</strong><span>Concept illustration · not completed work</span></figcaption></figure><figure class="gallery-item reveal">{picture('ceremony-concept','Illustration of an ornate floral mandap concept')}<figcaption><strong>Ceremony focal point</strong><span>Concept illustration · not completed work</span></figcaption></figure><figure class="gallery-item reveal">{picture('entrance-concept','Illustration of a terracotta floral event entrance concept')}<figcaption><strong>Arrival and entrance</strong><span>Concept illustration · not completed work</span></figcaption></figure></div></section>{cta('Have a different direction in mind?','Use these illustrations as a starting point, then share your actual event brief with the business.')}'''
page('concept-gallery.html','Concept Gallery | Saha Decorators Kolkata','Explore original, clearly labeled event and mandap decoration concept illustrations for Saha Decorators in Kolkata.',gallery)

faq=intro('Frequently asked questions','A clearer way<br><em>to get started.</em>','Here are practical questions to bring to a conversation with Saha Decorators.')+f'''<section class="section warm"><div class="container faq-list"><details class="reveal"><summary>What does Saha Decorators do?</summary><p>Independent local listings identify the business with decorating contractor and mandap decorator categories. Ask the team about the exact scope for your event.</p></details><details class="reveal"><summary>Can I request a specific decoration style?</summary><p>Share reference ideas and venue details directly. The business can tell you what may be possible; this website does not promise a particular design.</p></details><details class="reveal"><summary>Where is Saha Decorators located?</summary><p>Listings place the business at 59/60 Bagmari Road, Kankurgachi, Kolkata 700054. <a href="{MAP}" target="_blank" rel="noopener noreferrer">Open the location in Google Maps</a>.</p></details><details class="reveal"><summary>How can I ask about availability or a quote?</summary><p>Call <a href="{TEL}">+91 98301 27369</a> and share your date, venue and decoration brief. No pricing or availability is stated here without confirmation.</p></details><details class="reveal"><summary>Are the gallery images past projects?</summary><p>No. They are labeled original concept illustrations. Verified business work photographs were not available for use during preparation.</p></details></div></section>{cta()}'''
page('faq.html','FAQ | Saha Decorators Kolkata','Answers about Saha Decorators enquiries, location, decoration concepts and how to discuss availability directly.',faq)

contact=intro('Contact','Let’s talk about<br><em>your event.</em>','Call the verified business number or prepare a WhatsApp enquiry for your review and sending.')+f'''<section class="section warm"><div class="container contact-grid"><div class="contact-cards reveal"><div class="contact-card"><span class="icon-disc">{icon('phone')}</span><p class="eyebrow">Call directly</p><h2>+91 98301 27369</h2><p>Discuss your occasion, venue and what you need decorated.</p><a class="button" href="{TEL}">Call Saha Decorators {icon('arrow')}</a></div><div class="contact-card"><span class="icon-disc">{icon('whatsapp')}</span><p class="eyebrow">Message directly</p><h2>Start a WhatsApp chat</h2><p>Open the verified number in WhatsApp to discuss your event.</p><a class="button whatsapp-button" href="{WA}" target="_blank" rel="noopener noreferrer">{icon('whatsapp')} Send enquiry</a></div><div class="contact-card"><span class="icon-disc">{icon('pin')}</span><p class="eyebrow">Location</p><h2>Bagmari Road, Kolkata</h2><p>59/60 Bagmari Road, Kankurgachi, Kolkata 700054.</p><a class="inline-link" href="{MAP}" target="_blank" rel="noopener noreferrer">Open Google Maps {icon('arrow')}</a></div></div><form id="enquiry" class="enquiry-card reveal"><p class="eyebrow">Prepare your brief</p><h2>A good conversation starts with the details.</h2><p>Fill this in to prepare a WhatsApp enquiry on your device. It opens WhatsApp for your review; you must send it there. No information is stored or submitted by this website.</p><label for="name">Your name <span aria-hidden="true">*</span></label><input id="name" name="name" autocomplete="name" required minlength="2" placeholder="Your name"><label for="service">What would you like to discuss? <span aria-hidden="true">*</span></label><select id="service" name="service" required><option value="">Choose an option</option><option>Mandap decoration</option><option>Event decoration</option><option>Another decoration enquiry</option></select><label for="date">Event date (optional)</label><input id="date" name="date" type="date"><label for="message">Your message <span aria-hidden="true">*</span></label><textarea id="message" name="message" required minlength="10" rows="5" placeholder="Tell us about your occasion and venue"></textarea><button class="button whatsapp-button" type="submit">{icon('whatsapp')} Send enquiry</button><p id="form-feedback" role="status" aria-live="polite"></p><p class="form-note">WhatsApp opens for review; this site cannot confirm sending or booking. You can call the number above instead.</p></form></div></section>'''
page('contact.html','Contact Saha Decorators | Bagmari Road Kolkata','Call Saha Decorators at +91 98301 27369 or prepare a WhatsApp enquiry for event and mandap decoration in Kolkata.',contact)

(ROOT/'robots.txt').write_text(f'User-agent: *\nAllow: /\nSitemap: {BASE}sitemap.xml\n')
(ROOT/'sitemap.xml').write_text('<?xml version="1.0" encoding="UTF-8"?>\n<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'+''.join(f'  <url><loc>{BASE if f=="index.html" else BASE+f}</loc></url>\n' for f,_ in nav)+'</urlset>\n')
(ROOT/'.nojekyll').write_text('')
(ROOT/'README.md').write_text('''# Saha Decorators website concept\n\nStatic HTML, CSS and JavaScript site for the Saha Decorators lead in the Cloudempire Web Dev Leads Dashboard (row 9). The illustrations and logo are **proposed visual concepts**, not official branding or photographs of business work. See `docs/SOURCES.md` for verified facts and limitations.\n\nRun locally: `python -m http.server 8000` from this directory, then open `http://localhost:8000/`.\n''')
(ROOT/'docs').mkdir(exist_ok=True)
(ROOT/'docs'/'SOURCES.md').write_text('''# Sources and verification — 9 October 2026\n\n- Lead sheet: “Cloudempire Web Dev Leads Dashboard”, `Form Responses 1`, row 9. Business name Saha Decorators; locality Ultadanga / Bagmari Road; sector Event / mandap decoration; phone +91 98301 27369. No existing website, email, social profile, attachment, or WhatsApp label supplied.\n- [BharatiBiz](https://www.bharatibiz.com/en/saha-decorators_6S-098301-27369): exact name, mobile number, Bagmari Road/Kankurgachi location. Lists an email and hours, but these were not independently verified, so omitted. Site returned 429 to direct fetch; indexed content was available.\n- [India Industry](https://www.indiaindustry.biz/company-saha-decorators-in-kolkata-22731): exact business name, 59/60 Bagmari Road, Kankurgachi, Kolkata 700054; decorating contractors/mandap decorators. Lists a different landline, omitted because not in the sheet.\n- [ClickedIndia](https://www.clickedindia.net/qrbdo3qq1d/saha-decorator-kolkata.html): same 59/60 Bagmari Road address, wedding/flower/decorator category.\n- [Justdial gallery](https://www.justdial.com/Kolkata/Saha-Decorator-Near-Ultadanga-Foot-Bridge-Kankurgachi/033P28625_BZDET/photos): same street address but names business “Saha Decorator” and classifies it as catering; gallery advertises images, but originals/context could not be verified. No Justdial images, reviews, claimed rating, opening hours, business age, or catering claims used.\n- Google Maps address link on site is an address search, not a verified business profile. A matching Google Business profile, genuine attributable portfolio photos, original logo, and individual reviews were not confirmed. No unrelated search images used.\n- On 9 October 2026, the signed-in WhatsApp Web session opened a chat to the exact +91 98301 27369 number listed in the lead sheet and matching independent business directories. The chat header showed that exact number. Registration alone does not establish identity, so the sheet and directory agreement provides the corroboration. The site offers `https://wa.me/919830127369`, an enquiry draft for review, and a separate `tel:` call option. No claim of business approval is made.\n\n## Asset origins\n\n- `assets/logo.svg`, `assets/favicon.svg`: newly drawn proposed logo based on an arch motif; not official or business approved.\n- `assets/mandap-concept-*`: AI-generated conceptual mandap illustration for this website, from `generated_images/exec-058c1a0e-aa22-43ae-8d8a-a3b8ab2cdeeb.png`.\n- `assets/ceremony-concept-*`: AI-generated conceptual mandap illustration, from `generated_images/exec-b985f726-91c8-4fab-b6dc-1dc84d0a739e.png`.\n- `assets/entrance-concept-*`: AI-generated conceptual entrance illustration, from `generated_images/exec-9ca1e271-0c7c-4f27-aa5b-e3c8e985c9a0.png`.\n\nEvery generated image is visibly labeled “Illustration” and no image is described as completed work.\n''')
